---

ethernet_interface: eth1
version: bionic
mariadb_socket: /var/run/mysqld/mysqld.sock

boost: libboost-all-dev
cmake: cmake
development_tools: build-essential
expect: expect
file: file
jemalloc: libjemalloc1
libaio: libaio1
lz4_devel: libroslz4-dev
lz4: liblz4-tool
mariadb_backup: mariadb-backup
mariadb_client: mariadb-client
mariadb_columnstore_api: mariadb-columnstore-api-cpp
mariadb_columnstore_client: mariadb-columnstore-client
mariadb_columnstore_common: mariadb-columnstore-common
mariadb_columnstore_gssapi: mariadb-columnstore-gssapi-server
mariadb_columnstore_libs: mariadb-columnstore-libs
mariadb_columnstore_maxscale: mariadb-columnstore-maxscale-cdc-adapters
mariadb_columnstore_platform: mariadb-columnstore-platform
mariadb_columnstore_server: mariadb-columnstore-server
mariadb_columnstore_shared: mariadb-columnstore-shared
mariadb_columnstore_storage: mariadb-columnstore-storage-engine
mariadb_columnstore_tools: mariadb-columnstore-tools
mariadb_rocks: mariadb-plugin-rocksdb
mariadb_server: mariadb-server
mariadb_spider: mariadb-plugin-spider
mariadb: mariadb*
maxscale_cdc_connector: maxscale-cdc-connector
mlocate: mlocate
mysql_python: python-mysqldb
nano: nano
net_tools: net-tools
nmap: nmap
numactl_libs: libnuma1
openssl: openssl
perl_DBI: libdbi-perl
perl: perl
pid: /var/run/mysqld/mysqld.pid
pigz: pigz
readline_dev: libreadline-dev
rsync: rsync
snappy: libsnappy1v5
socat: socat
socket: /var/run/mysqld/mysqld.sock
tcl: libtcl8.6
tcp_wrappers_devel: libwrap0-dev
tzdata: tzdata
unzip: unzip
zlib: zlibc
